// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/CaiqueRibeiro/product-api/internal/infra/database"
	"github.com/CaiqueRibeiro/product-api/internal/infra/webserver/handlers"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func NewProductHandler(db *gorm.DB) *handlers.ProductHandler {
	productRepository := database.NewProductRepository(db)
	productHandler := handlers.NewProductHandlers(productRepository)
	return productHandler
}

func NewUserHandler(db *gorm.DB) *handlers.UserHandlers {
	userRepository := database.NewUserRepository(db)
	userHandlers := handlers.NewUserHandlers(userRepository)
	return userHandlers
}

// wire.go:

var setProductRepositoryDepencency = wire.NewSet(database.NewProductRepository, wire.Bind(new(database.ProductRepositoryInterface), new(*database.ProductRepository)))

var setUserRepositoryDepencency = wire.NewSet(database.NewUserRepository, wire.Bind(new(database.UserRepositoryInterface), new(*database.UserRepository)))
